spring:
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=c-mart;encrypt=true;trustServerCertificate=true;sslProtocol=TLSv1.2
    username: sa
    password: 123456
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
      database-platform: org.hibernate.dialect.SQLServer2012Dialect
jwt:
  secret: 2b44b0b00fd822d8ce753e54dac3dc4e06c2725f7db930f3b9924468b53194dbccdbe23d7baa5ef5fbc414ca4b2e64700bad60c5a7c45eaba56880985582fba4
  expiration : 36000000
app:
  google:
    api:
      key: AIzaSyBzBm8v-tTnoWgipxIRqGZfKG60bn7MA1g