spring:
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=c-mart;encrypt=true;trustServerCertificate=true;sslProtocol=TLSv1.2
    username: sa
    password: 123456
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.SQLServer2012Dialect
